name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag furgandogan/gardiyan:latest
    - name: Push the Docker image
      run: docker push furgandogan/gardiyan:latest
